- src/table.rs
- src/transactions.rs
These should only be queried in a transaction, so that they have the
proper isolation level
> Move len() and is_empty() methods to ReadTransaction

- benches/syscall_benchmark.rs
Removes some extra allocations that lmdb & mmap can avoid
> Make read/write benchmark more fair

- src/error.rs
> Implement std::error::Error for our custom Error

- src/error.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/storage.rs
> Cleanup drop() implementation to avoid double panics

- src/tree_store/page_store/page_manager.rs
- tests/integration_tests.rs
Previously allocations were replayed followed by frees, but the order of
allocations and frees matters
> Fix replay of allocations into secondary allocator state

- src/tree_store/btree_base.rs
- src/tree_store/btree_utils.rs
Consolidating all the key data improve cache hit rate and increases
lookup performance by ~20%
> Optimize leaf node structure

- src/tree_store/btree_base.rs
This could happen when a page was split with the partials being inserted
entirely before the old entries
> Prevent underflow

- src/multimap_table.rs
- src/tree_store/page_store/page_manager.rs
- tests/integration_tests.rs
> Return OutOfSpace instead of panicking when initial size is too small

- src/tree_store/page_store/page_manager.rs
- src/tree_store/storage.rs
It strikes me know that this might actually not belong on DbStats, since it doesn't change during the life of the database, so it might be better as a method on `Database`. What do you think?
Calling `DbStats::new` with a bunch of usizes that are easy to mix up seemed error-prone, so I changed initialization to use the constructor directly, which is harder to mess up.
> Include page size in db stats

- src/multimap_table.rs
- src/table.rs
- src/tree_store/btree_base.rs
- src/tree_store/btree_iters.rs
- src/tree_store/btree_utils.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/storage.rs
I've never seen `pub(in crate)` before, so I could definitely be wrong about this, but I think it's equivalent to `pub(crate)`.
This was done with `sed -i 's/pub(in crate)/pub(crate)/g' **/*.rs`.
> Use pub(crate)

- benches/common.rs
- examples/int_keys.rs
- src/db.rs
- src/table.rs
- src/tree_store/btree_utils.rs
- src/tree_store/page_store/page_manager.rs
- tests/basic_tests.rs
- tests/integration_tests.rs
- tests/multimap_tests.rs
- tests/multithreading_tests.rs
This PR changes functions that take table definitions to take them by value, so you don't have to add a `&`, and implements `Copy` and `Clone` for table definitions. We have to implement copy and clone ourselves, because the derive macro can't figure out that it can copy and clone the value even when the type arguments aren't copy and clone, because we only use pass them to phantom values.
> Pass table definitions by value

- Cargo.toml
- src/db.rs
- src/tree_store/page_store/mmap.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/storage.rs
I'm not sure how you wanted to expose this to users, i.e. if it should be the default on macos because msync is awful, or by introducing a different commit type, but wanted to get a draft PR up. This code worked with the simple repo case, and I'll try it with the full ord database soon.
> Use F_BARRIERFSYNC on macos

- Cargo.toml
- benches/lmdb_benchmark.rs
- benches/syscall_benchmark.rs
I'm having trouble preventing the table from wrapping, opened an issue about it (https://github.com/Nukesor/comfy-table/issues/66) but here's what it looks like so far:
```
+--------------------+------+------+------+
|                    | redb | lmdb | sled |
+=========================================+
| bulk load          | 4136 | 1235 | 1428 |
|                    | ms   | ms   | 2ms  |
|--------------------+------+------+------|
| individual writes  | 50ms | 10ms | 3547 |
|                    |      |      | ms   |
|--------------------+------+------+------|
| batch writes       | 5495 | 3010 | 1126 |
|                    | ms   | ms   | 8ms  |
|--------------------+------+------+------|
| random reads       | 1106 | 1108 | 1703 |
|                    | ms   | ms   | ms   | …
```
> Print table of benchmark results

- tests/mmap_tests.rs
redb will likely rely on this behavior in the future
> Add test that concurrently reloads an mmap'ed region

- Cargo.toml
I was looking at #211 and noticed that I accidentally made comfy-table a dependency, not a dev-dependency. This PR fixes that.
> Make comfy-table a dev dependency

- src/db.rs
This is a pretty common pattern where a type has a `builder` method that returns an instance of the corresponding builder. It's nice because you don't need to know about where the builder is or what it's called, makes it more discoverable, and avoids an extra import.
> Add convenience method to return database builder

- benches/common.rs
- examples/int_keys.rs
- src/db.rs
- src/multimap_table.rs
- src/table.rs
- src/tree_store/btree_utils.rs
- src/tree_store/page_store/page_manager.rs
- tests/basic_tests.rs
- tests/integration_tests.rs
- tests/multimap_tests.rs
- tests/multithreading_tests.rs
Adds support for reopening a table during a write transaction. Also
fixes the fact that Table objects could outlive their WriteTransaction
Fixes #208
> Add support for reopening a table

- tests/basic_tests.rs
As far as I can tell this can't be fixed, because of the ambiguity
between Range<T> and Range<&T>
> Remove TODOs

- fuzz/Cargo.toml
- fuzz/fuzz_targets/common.rs
Use a variant of the binomial distribution, instead of the uniform
distirbution. This also makes the fuzzer ~100x faster because the mean
value size is much smaller
> Change fuzzer value length distribution

- benches/int_benchmark.rs
- benches/large_values_benchmark.rs
- benches/lmdb_benchmark.rs
- benches/syscall_benchmark.rs
/tmp might be mounted as a tmpfs, which would skew the results.
Fixes #282
> Move benchmark temp files to CWD

- src/transactions.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/table_tree.rs
- tests/integration_tests.rs
Re-opening a table during a write transaction caused the new Table
instance to return stale read results
> Fix bug that caused stale reads

- benches/lmdb_benchmark.rs
- fuzz/fuzz_targets/common.rs
- fuzz/fuzz_targets/fuzz_redb.rs
- src/db.rs
- src/lib.rs
- src/multimap_table.rs
- src/table.rs
- src/tree_store/btree.rs
- src/tree_store/btree_base.rs
- src/tree_store/btree_mutator.rs
- src/tree_store/mod.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/xxh3.rs
- src/tree_store/table_tree.rs
This commit strategy uses a merkle tree checksum over the data +
primary/secondary metadata. This allows a commit to be performed with a
single fsync, since the checksum can be read in the event of a crash to
determine whether the data was written out completely
Fixes #253
> Implement single phase commit with checksum

- src/tree_store/page_store/grouped_bitmap.rs
- src/tree_store/page_store/page_allocator.rs
This makes a future optimization possible, without a file format change,
in which we skip initializing new region allocators by relying on the OS
initializing them to zero
> Invert bit pattern of grouped bitmap

- Cargo.toml
- benches/mmap_page_size_benchmark.rs
Fixes #345 
Yes, we definitely want this to be configurable and default to the native page size. Benchmark results below from my Ubuntu desktop with 4k native pages:
```
page_size: 512B. Wrote 128MiB bytes in 909ms (140MiB/s)
page_size: 1KiB. Wrote 128MiB bytes in 453ms (282MiB/s)
page_size: 2KiB. Wrote 128MiB bytes in 244ms (524MiB/s)
page_size: 4KiB. Wrote 128MiB bytes in 141ms (907MiB/s)
page_size: 8KiB. Wrote 128MiB bytes in 128ms (1000MiB/s)
page_size: 16KiB. Wrote 128MiB bytes in 122ms (1GiB/s)
page_size: 32KiB. Wrote 128MiB bytes in 118ms (1GiB/s)
page_size: 64KiB. Wrote 128MiB bytes in 124ms (1GiB/s)
page_size: 128KiB. Wrote 128MiB bytes in 128ms (1000MiB/s)
```
> Add page size benchmark

- src/db.rs
- src/tree_store/page_store/buddy_allocator.rs
- src/tree_store/page_store/mmap.rs
- src/tree_store/page_store/mmap/unix.rs
- src/tree_store/page_store/mmap/windows.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/xxh3.rs
- tests/integration_tests.rs
- tests/mmap_tests.rs
1. Windows requires that file mappings to files on disk have a length > 0. This means that several tests immediately fail since they start with an empty file.
2. The Unix implementation truncates files to both decrease and increase the size of the mapped memory and then remaps and asserts that the base pointer is the same so that files can be resized while also being read from concurrently. While it's _possible_ that increasing the file size on Windows can be accomplished with [some "lightly" documented internal kernel functions](https://stackoverflow.com/a/55068177), _decreasing_ the size of the file is (AFAIK) impossible without unmapping the file first.
This provides initial support for Windows that passes _almost_ all tests, I've disabled `regression14 + 15` tests since they both …
> Add initial Windows support

- src/db.rs
- src/transactions.rs
- tests/basic_tests.rs
I replaced the live write transaction `Mutex` with an `RwLock` so that writes can be initiated in parallel on different threads, but will block each other. I'm not sure if this is right, since there are a lot of subtleties with things like this.
Also, I was thinking that `WriteTransaction::new` should be safe, and should only take a reference to the database, and should grab the `RwLock` and allocate a new transaction ID, instead of spreading the safety concerns between `Database::begin_write` and `WriteTransaction::new`.
Depends on #370.
> Add write lock

- src/tree_store/page_store/mmap/unix.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/utils.rs
This improves performance by ~2x for databases that do not fit in memory
> Use madvise(RANDOM)

- Makefile
Makefile no longer requires nightly toolchain to be installed for all recipes, and now only requires it for the fuzz and fuzz_coverage targets
Fixes #372
> Fix Makefile warning

- fuzz/fuzz_targets/fuzz_redb.rs
- src/db.rs
- src/transactions.rs
- tests/integration_tests.rs
This allows users to construct certain race-free savepoint scenarios, and fixes several races in the fuzzer
> Move savepoint methods to WriteTransaction

- src/transactions.rs
- src/tree_store/page_store/savepoint.rs
This ensures that the Savepoint being restored was captured from the same Database
Fixes #413
> Add assert to restore_savepoint()

- justfile
This is nice for development. `just watch` re-runs the tests whenever it detects that a file has changed using `cargo-watch`. (`cargo install cargo-watch`) You can pass any cargo command, e.g.,`just watch check` if you just want to check for compilation errors.
> Add watch recipe

- src/multimap_table.rs
- src/table.rs
- src/tree_store/page_store/xxh3.rs
- tests/basic_tests.rs
- tests/multimap_tests.rs
This adds `ReadableTable::iter` and `ReadableMultimapTable::iter` that both just call `self.range(..)`. I was hoping to implement `IntoIter` for both, so that they could be used in for loops, but couldn't because `range` can fail. An `iter` function seems relatively common, c.f. `Vec::iter` and `BTreeMap::iter`. I do `range(..)` a bunch, so this is nice to have. Also, `range(..)` can't infer the type, so you always have to use `range(MINIMUM_VALUE..)` to get it to work.
> Add iter method for iterating over all values in table

- docs/design.md
- src/db.rs
- src/tree_store/page_store/header.rs
- src/tree_store/page_store/layout.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
Creates an owned copy of all the headers and allocator state, so that we don't need to references it directly in the mmap. This reduces the safety problems mentioned in #450
> Cache metadata

- src/error.rs
- src/tree_store/mod.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
Return UpgradeRequired when the file format is too old instead of Corrupted
Fixes #479
> Differentiate older file format errors

- README.md
Since 57e4d20607e34933f1a80ac06eab9ba61f515af6 create is safe.
and fixed compilation error. :)
> Fix compilation of code in readme.md.

- src/db.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/table_tree.rs
- src/types.rs
- tests/basic_tests.rs
> Option support and alignment future proofing

- src/tree_store/page_store/mmap.rs
Because libc lacks the Android platform api, it cannot be used on Android. Modify the compilation condition to be compatible with Android platform.
> Android compatible

- Cargo.toml
- src/tree_store/page_store/cached_file.rs
This improves contended read performance by 10-20%, when the feature is disabled
> Gate cache hit counting with feature flag

- src/multimap_table.rs
Currently the following code doesn't work:
```rust
fn get_it(&self) -> impl Iterator</* ... */> {
let key = /* ... */;
self.table.get(key).expect("Unable to create iterator")
}
```
where `self.table` is a `MultimapTable<K, V>`.
This is because the signature of `ReadableMultimapTable::get` actually borrows it's `key` argument due to using `K::SelfType<'a>`, where the receiver is `&'a self`. This PR adds a new `'b` lifetime to use for the `K::SelfType`, just like the `range` method below it.
This is technically a breaking change due to the `ReadableMultimapTable` trait being public and not sealed. Aside from this however, I believe it doesn't prevent any code that compiled from compiling, nor changes any behavior.
> Fixed `ReadableMultimapTable::get`'s return type borrowing `key` argument

- src/transaction_tracker.rs
- src/transactions.rs
- src/tree_store/page_store/page_manager.rs
Pages from the freed-tree itself are now immediately freed, when posisble, rather than being deferred to a future transaction. This is possible as long as there are no active savepoints. When there are active savepoints we still have to defer the frees.
> Optimize page freeing

- clippy.toml
- src/lib.rs
- tests/integration_tests.rs
usize should always be explicitly serialized as u32 or u64
> Disallow usage of usize::to_le_bytes()

- .github/workflows/ci.yml
- Cargo.toml
- justfile
- src/db.rs
- src/lib.rs
- src/table.rs
- src/transactions.rs
- src/tree_store/btree.rs
- src/tree_store/page_store/file_lock/mod.rs
- src/tree_store/page_store/file_lock/unix.rs
- src/tree_store/page_store/header.rs
- src/tree_store/page_store/page_manager.rs
- tests/basic_tests.rs
- tests/integration_tests.rs
- tests/multimap_tests.rs
- tests/multithreading_tests.rs
Adds experimental WASI support. Requires nightly and file locking is currently a no-op, at least for the immediate future (needs to get implemented upstream).
Partially fixes #507
> Add WASI support

- src/db.rs
- src/transactions.rs
- src/tree_store/page_store/cached_file.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/region.rs
This remove an unncessary file read on cache misses when a page is allocated for re-use. Benchmarks show a 3-10% improvement in throughput
> Optimize write performance

- src/tree_store/page_store/page_manager.rs
- tests/integration_tests.rs
Fixes a crash that can occur when re-openning a database that is small in size
Fixes #629
> Fix crash when re-openning a database

- src/multimap_table.rs
- src/table.rs
- tests/basic_tests.rs
also add `generic_signature_lifetimes` test for it
---
For the latest version, the `write_key_generic` function won't compile:
```rust
error[E0597]: `buf` does not live long enough
--> src/main.rs:27:31
|
20 |         key: K::SelfType<'_>,
|         --- has type `<K as RedbValue>::SelfType<'1>`
...
23 |         let buf = [1, 2, 3];
|             --- binding `buf` declared here
...
27 |             table.insert(key, buf.as_slice()).unwrap();
|             ------------------^^^^^^^^^^^^^^-
|             |                 |
|             |                 borrowed value does not live long enough
|             argument requires that `buf` is borrowed for `'1`
...
30 |     }
|     - `buf` dropped here while still borrowed
```
> fix(insert sig lifetime): key and value should have different lifetimes

- Cargo.toml
without pinning the version, Cargo chooses the latest semver compatible version, which is 1.1.0 - defeating the intention of the backwards-compatibility tests.
> Pin redb1 at 1.0.0

- Cargo.toml
- src/db.rs
- src/multimap_table.rs
- src/table.rs
- src/transactions.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/region.rs
This enables using this library with e.g. [`cap-std`](https://docs.rs/cap-std) which avoids path-based access in favour of a capability-based approach.
I am not sure about the name, but `open` while probably most fitting is already taken for the path-based approach. Alternatives I considered were `from_file`, `access`, `mount` and `open_or_init`.
I added another commit to ensure that the build is Clippy-clean before submitting the PR. Please let me if know if you like me to drop that from the PR as it is admittedly unrelated. (Bumping `fastrand` resolves a few warnings about unnecessary mutability in the LMDB benchmark.)
> Allow opening a database using a file handle instead of a path

- .github/workflows/ci.yml
- Cargo.toml
- src/tree_store/page_store/bitmap.rs
matches Debian 13 distributed Rust.
there were no particular dependencies on Rust 1.67.
fixes #670
> lower MSRV to 1.66

- src/multimap_table.rs
- src/table.rs
- src/tree_store/btree.rs
This seems correct to me, but I am not entirely sure. Would these stats be way off?
Adds a `stats` method to `ReadableTable` and `ReadableMultimapTable`.
Closes #671
> feat: add per-table stats

- src/lib.rs
Just copied over some of the readme to the rustdoc page as it is fairly common to just look up crates on docs.rs if you are contributing to a project
> chore: add small intro on rustdoc

- src/tree_store/btree_base.rs
- src/types.rs
- tests/basic_tests.rs
> Implement RedbKey for Option<T: RedbKey>

- src/error.rs
> Clarify InvalidSavepoint meaning

- src/db.rs
- src/table.rs
- src/transactions.rs
> Implement Debug for Table and ReadOnlyTable

- src/tree_store/page_store/page_manager.rs
The read ref count tracking could leak if a storage error occurred
> Fix errant panic with debug_assertions

- src/db.rs
- src/error.rs
- src/lib.rs
- src/tree_store/page_store/header.rs
This allows the user to abort the repair process and receive progress notifications
Fixes #639
> Add option to set a repair callback

- src/multimap_table.rs
- src/table.rs
- src/transactions.rs
- tests/basic_tests.rs
> Fix panic when calling delete_table() for a table that is open

- src/types.rs
- tests/basic_tests.rs
Just noticed that key value impls for char were missing, so I added them.
> Implement RedbValue and RedbKey for char

- src/multimap_table.rs
- src/tree_store/btree_base.rs
- src/tree_store/btree_mutator.rs
- tests/integration_tests.rs
When selecting the page size to allocate when building a leaf(s) page space for offsets were still being allocated for fixed width types. This lead to those types having leaves that were much larger than necessary, and worse they could grow without bound eventually leading to a panic when the page overflowed the maximum 2^16 storable pairs.
Fixes #719
> Improve performance and fix panic

- src/lib.rs
- src/multimap_table.rs
- src/table.rs
- src/transactions.rs
- src/tree_store/btree.rs
- tests/basic_tests.rs
> New untyped stats API

- src/tuple_types.rs
Macros can be called with `()`, `{}`, and `[]`. Using `{}` is slightly more idiomatic for things that expand to items (impl blocks, struct definitions, etc), and has the benefit that `cargo fmt` doesn't try to format them.
> Use curly braces for `tuple_impl!` calls

- src/db.rs
- src/multimap_table.rs
- src/table.rs
- src/tree_store/btree.rs
- src/tree_store/btree_iters.rs
- tests/basic_tests.rs
- tests/multimap_tests.rs
> Add lifetime-free range methods

- CHANGELOG.md
- docs/design.md
- src/db.rs
- src/error.rs
- src/multimap_table.rs
- src/table.rs
- src/transactions.rs
- src/tree_store/btree.rs
- src/tree_store/btree_base.rs
- src/tree_store/btree_mutator.rs
- src/tree_store/mod.rs
- src/tree_store/page_store/header.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/savepoint.rs
- src/tree_store/table_tree.rs
- tests/backward_compatibility.rs
This introduces a counter for the length of tables, so that len() is constant time instead of linear in the size of the table
> Change file format to version 2

- Cargo.toml
- src/db.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/region.rs
- tests/integration_tests.rs
> Fix check_integrity() to return Ok(true) when no repair was performed

- benches/common.rs
- src/tree_store/btree_base.rs
- src/tree_store/btree_mutator.rs
This matches all our other APIs like TableDefinition
> Require V: 'static on AccessGuard

- README.md
> :memo: Fix benchmark source should not be in table

- src/types.rs
- tests/basic_tests.rs
> Implement Key and Value for String

- .github/workflows/ci.yml
- src/db.rs
- src/error.rs
- tests/integration_tests.rs
> Fix panic in compact() when read transaction is in progress

- src/tree_store/btree_base.rs
- src/tree_store/btree_mutator.rs
- src/tree_store/page_store/base.rs
- src/tree_store/page_store/cached_file.rs
~~The second commit removes any per-access overhead to `WritablePage` but at the cost of some unsafe code relying on the uniqueness that was asserted once by calling `Arc::try_unwrap` before this change.~~
> RFC: Avoid double-indirection of Arc<Vec<u8>> by using Arc<[u8]> directly

- src/tree_store/page_store/cached_file.rs
Just after dirty pages have been written out to disk, they are currently discard and need to be read in again when these pages are accessed in the future.
This changes moves them into the read cache instead thereby keeping the clean data available and cache hot in memory.
It turned out that this was also what was making direct I/O slower in #808, i.e. this was not that noticeable when buffered I/O is use because the pages were read back in from the kernel page cache most of the time but it should be a win in both scenarios.
> Move cleaned pages into read cache instead of discarding them.

- src/transactions.rs
- src/tree_store/btree.rs
- src/tree_store/table_tree.rs
- tests/integration_tests.rs
Previously it always returned ReadTransactionStillInUse
Fixes #812
> Fix ReadTransaction::close()

- Cargo.toml
- examples/bincode_keys.rs
The first commit is just to make current Clippy build cleanly and can be drop if so desired.
Not sure if you want such additions as this could be considered "playing favourites" with a particular format and you might see requests to add many others. OTOH, Bincode is a pretty decent default for binary serialization formats of small messages.
> RFC: Add wrapper type to handle keys and values based on bincode serialization

- src/multimap_table.rs
- src/table.rs
- src/transactions.rs
- src/tree_store/mod.rs
- src/tree_store/page_store/base.rs
- src/tree_store/page_store/mod.rs
- tests/integration_tests.rs
StorageError::ValueTooLarge will now be returned for key-value pairs that exceed 3.75GiB
Fixes #819
> Fix panic when inserting pair exceeding ~4GiB

- src/db.rs
- src/transaction_tracker.rs
- src/transactions.rs
> Downgrade many log messages from info! to debug!

- src/transactions.rs
- src/tree_store/page_store/page_manager.rs
- tests/integration_tests.rs
> Fixes to savepoint restoration

- src/db.rs
- src/error.rs
- src/tree_store/page_store/cached_file.rs
If a transient I/O error occurred during the updates to a btree, but then I/O errors did not occur when the Database was dropped. It was possible for the file to be flushed with a clean recovery flag and broken transaction, leading to corruption
> Make all I/O errors fatal. Fixes potential corruption

- benches/lmdb_benchmark.rs
Compared to redb (and sled), RocksDB gets way too little cache capacity (32MB), which negatively impacts its read performance. Setting it to 4 GB (same as redb) gives it a 1.5x read performance boost on my system.
I haven't updated the readme, because it's system dependent, so you would need to rerun it on yours.
> benchmark: increase rocksdb block cache capacity

- docs/design.md
Note: there are currently some bugs in the implementation. So it does not fully match the design
> Add documentation on page reclamation

- src/transactions.rs
- src/tree_store/page_store/buddy_allocator.rs
- src/tree_store/page_store/layout.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/region.rs
- src/tree_store/page_store/savepoint.rs
- src/tree_store/table_tree.rs
Pages allocated in the system tree or freed tree when the savepoint was captured are currently leaked, because they are in a pending free state, and so do not appear in the diff of the allocator state, but they are also curretly being dropped from the freed tree.
This fixes the leak, but make restore_savepoint() slower
> Fix leak of pages in restore_savepoint()

- src/db.rs
- src/transactions.rs
- src/tree_store/page_store/page_manager.rs
If the database file was truncated because there was excess space, during the repair, check_integrity() returned Ok(false)
> Fix false positive in check_integrity()

- fuzz/fuzz_targets/fuzz_redb.rs
- src/transactions.rs
- src/tree_store/page_store/bitmap.rs
- src/tree_store/page_store/buddy_allocator.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/region.rs
> Improve fuzzer to detect leaked pages

- Cargo.toml
- benches/common.rs
- benches/int_benchmark.rs
- benches/large_values_benchmark.rs
- benches/lmdb_benchmark.rs
- benches/syscall_benchmark.rs
`just bench` failed on my machine (M1 Pro, 32GB RAM)
```console
➜  redb git:(master) ✗ just bench
...
lmdb-rkv: Bulk loaded 1000000 items in 1395ms
lmdb-rkv: Wrote 100 individual items in 11ms
lmdb-rkv: Wrote 100 x 1000 items in 3364ms
lmdb-rkv: len() in 0ms
lmdb-rkv: Random read 1000000 items in 1063ms
lmdb-rkv: Random read 1000000 items in 1045ms
error: bench failed, to rerun pass `--bench lmdb_benchmark`
Caused by:
process didn't exit successfully: `/Users/shekhirin/Projects/redb/target/release/deps/lmdb_benchmark-9bace23009390253 --bench` (signal: 11, SIGSEGV: invalid memory reference)
error: Recipe `bench` failed on line 34 with exit code 101
```
So I decided to try out [heed](https://github.com/meilisearch/heed) as an alternative LMDB wrapper library. It's more maintained and …
> chore: use heed for LMDB in benchmark

- Cargo.toml
- README.md
- benches/lmdb_benchmark.rs
This PR displays the best result in bold and gives you the size of the temporary files after all benchmarks, so you can get a rough idea of their total size. I also make sure the table is in Markdown format, making it easier to copy and paste into the README.
|                           | redb     | lmdb         | rocksdb        | sled       | sanakirja    |
|---------------------------|----------|--------------|----------------|------------|--------------|
| bulk load                 | 3.90s    | 1.25s        | 7.07s          | 5.57s      | **1.13s**    |
| individual writes         | 459.81ms | 8.09ms       | **4.34ms**     | 406.12ms   | 57.15ms      |
| batch writes              | 4.78s    | 2.72s        | **272.26ms**   | 1.41s      | 4.70s        |
| len()                     | …
> Better markdown benchmarks

- src/multimap_table.rs
- src/tree_store/btree.rs
- src/tree_store/btree_base.rs
- src/tree_store/mod.rs
- src/tree_store/table_tree_base.rs
Previously the subtrees of a multimap table were skipped during compaction
> Improve compaction

- benches/lmdb_benchmark.rs
Note: compact() is currently too slow to practically run with the default 1M elements. It takes 43secs on my computer when set to 1000 elements
> Add compaction to lmdb_benchmark

- benches/common.rs
- src/db.rs
- src/multimap_table.rs
- src/transactions.rs
- src/tree_store/btree.rs
- src/tree_store/mod.rs
- src/tree_store/page_store/base.rs
- src/tree_store/table_tree.rs
- src/tree_store/table_tree_base.rs
> Major performance improvement to compact() 

- src/db.rs
- src/tree_store/page_store/cached_file.rs
- src/tree_store/page_store/page_manager.rs
- tests/integration_tests.rs
Fixes a panic in commit() or abort() which would occur if a previous commit() or abort() had failed due to an I/O error
Fixes #857
> Fix panic and return PreviousIo error instead

- src/db.rs
- src/tree_store/page_store/savepoint.rs
The freed tree referenced by a savepoint should not be accessed, because its pages are not versioned -- they are immediately freed after a durable commit
> Fix potential panic in repair

- docs/design.md
Since redb no longer uses mmap, I think this reference to msync can be removed.
> Remove reference to msync in design doc

- src/table.rs
- src/tree_store/btree.rs
- tests/integration_tests.rs
This change makes these methods almost 2x faster, by reducing the number of tree traversals from two to one.
> Optimize first() and last()

- src/tree_store/page_store/cached_file.rs
A race could cause the read cache tracking to overcount, eventually evicting the entire read cache, and degenerating into always reading from disk.
Fixes #870
> Fix leak in read cache tracking

- src/tree_store/page_store/cached_file.rs
- src/tree_store/page_store/lru_cache.rs
> Cache optimizations

- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/region.rs
When allocating a new region tracker, we need to free the old one.  Also, when recreating the region tracker during repair, it has to be large enough for the actual number of regions (which might be more than INITIAL_REGIONS).
I've expanded the existing out_of_regions() test case to exercise both of these code paths; the test will fail without these fixes.
> Fix region tracker page leak and initial sizing

- src/tree_store/page_store/page_manager.rs
When shutting down due to a panic, don't mark the database as clean; just treat it like a crash and let the recovery code run next time. This avoids page leaks and possibly other database corruption, depending on where the panic happens.
> Panic isn't a clean shutdown

- src/tree_store/btree_base.rs
During repair, it's normal to encounter a partially-written tree, which can contain arbitrary invalid data.  We can't crash when that happens; we need to gracefully fail so the repair can try the other commit slot instead.
This first batch of fixes only covers the crashes most likely to occur in practice: the ones that can happen on a 64-bit machine, without malicious input.  There are several more arithmetic overflows that can only happen on 32-bit machines, which are simple to fix but I haven't done yet (I can probably look at these after #878).  There are also a number of trickier crashes that can only happen when there's corrupt data with a valid checksum, which is unlikely to happen accidentally but definitely possible with malicious input.  #878 will greatly improve the situation …
> Fix several crashes in repair from corrupted pages

- .gitignore
- src/complex_types.rs
- src/db.rs
- src/error.rs
- src/lib.rs
- src/multimap_table.rs
- src/table.rs
- src/transaction_tracker.rs
- src/transactions.rs
- src/tree_store/btree.rs
- src/tree_store/btree_base.rs
- src/tree_store/btree_iters.rs
- src/tree_store/btree_mutator.rs
- src/tree_store/page_store/base.rs
- src/tree_store/page_store/bitmap.rs
- src/tree_store/page_store/buddy_allocator.rs
- src/tree_store/page_store/cached_file.rs
- src/tree_store/page_store/layout.rs
- src/tree_store/page_store/lru_cache.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/region.rs
- src/tree_store/page_store/savepoint.rs
- src/tree_store/page_store/xxh3.rs
- src/tree_store/table_tree.rs
- src/tree_store/table_tree_base.rs
- src/types.rs
I like the pedantic clippy lints, since they often turn up things that are either a little suspicious, or which just have better alternatives.
I went through all the `clippy::pedantic` lints which weren't enabled, and one by one either denied or enabled them, usually with some kind of rationale. Sometimes I allowed lints that should probably be denied, either because they're subjective, or would take more knowledge of `redb` than I have to actually fix.
I tried to do each one in a separate commit, to keep things readable and let you review the rationale for each, which are in the commit messages.
Finally, I added `clippy::pedantic` to the `#![deny]` block, and tried to remove any `allow` which was not actually being triggered.
As of Rust 1.74, you can put lints in `Cargo.toml`, which is a …
> Turn on pedantic clippy lints where possible

- fuzz/fuzz_targets/fuzz_redb.rs
- src/transactions.rs
We never shrink the region tracker page, so it'll show up as a leak any time it grows larger than its initial size.  This isn't a useful leak to report, so just ignore it.
> Don't count the region tracker page when checking for leaks

- docs/design.md
- fuzz/fuzz_targets/common.rs
- fuzz/fuzz_targets/fuzz_redb.rs
- src/db.rs
- src/multimap_table.rs
- src/transactions.rs
- src/tree_store/btree.rs
- src/tree_store/btree_mutator.rs
- src/tree_store/page_store/header.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/table_tree.rs
- src/tree_store/table_tree_base.rs
Here's the PR for #878!
This adds a new durability level above Paranoid that doesn't require repair.  For now, it's just called "ParanoidPlus" -- not the most descriptive name, but it at least makes it very clear where it falls on the scale of commit speed vs. recoverability.  If you have a better name, let me know 😄
To avoid repair, Durability::ParanoidPlus commits need to save the allocator state somewhere.  We can't use the region headers, because we'd be overwriting them in place; we might crash partway through the overwrite, and then we'd need repair.  So we instead save the allocator state to a new table in the system tree.  Writing to the table is slightly tricky, because it needs to be done without allocating (see below), but other than that it's a perfectly ordinary transactional …
> Add set_quick_repair()

- src/db.rs
- src/tree_store/page_store/header.rs
- src/tree_store/page_store/page_manager.rs
Traditionally, redb has stored its allocator state in the region headers and region tracker page, which are only valid after a clean shutdown.  Now that we also have the allocator state table (which works even after a crash), it would be nice to use that exclusively.
This is the first step in that transition: making sure that after a clean shutdown, the allocator state is saved to both places.  Then, once enough time has passed, we can remove all support for reading and writing the old allocator state.
Even after the transition, any redb version will be able to open any database.  If the database has been opened at least once during the transition period, it'll open cleanly; otherwise it'll require repair, but it'll always work.
Note that this means we're saving the allocator state twice …
> Ensure quick-repair commit on shutdown

- benches/lmdb_benchmark.rs
> explicitly  set cache sizes

- src/tree_store/page_store/page_manager.rs
Now that we have #897, we no longer need special-case code to flush non-durable commits on shutdown, since Database::drop() now guarantees that the last commit before shutdown is a durable commit with quick-repair enabled.
> No need to flush non-durable commits anymore

- src/tree_store/page_store/page_manager.rs
When writing the allocator state table, it's better not to include the region tracker page as one of the allocated pages. Instead, we should allocate the region tracker page during quick-repair after loading the rest of the allocator state, exactly like we do for full repair.
This avoids an unlikely corruption that could happen for databases larger than 4 TB, if we crash on shutdown after writing out a new region tracker page number but before clearing the recovery_required bit. It also means that in the future, when we drop support for the old allocator state format, we'll be able to get rid of the region tracker page entirely instead of having to keep around some of the allocation code for compatibility.
> Don't mark the region tracker page as allocated

- src/db.rs
- src/tree_store/page_store/header.rs
- src/tree_store/page_store/page_manager.rs
- tests/integration_tests.rs
Previously we attempted to initialize the file with a new database
Fixes #913
> Return InvalidData if magic number does not match

- src/db.rs
- src/lib.rs
- src/tree_store/page_store/cached_file.rs
- src/tree_store/page_store/page_manager.rs
When the "cache_metrics" feature is enable this exposes the number of cache evictions
Fixes #910
> Add Database::cache_stats()

- src/transactions.rs
- src/tree_store/btree.rs
- src/tree_store/mod.rs
- src/tree_store/page_store/bitmap.rs
- src/tree_store/page_store/buddy_allocator.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
- src/tree_store/page_store/region.rs
- src/tree_store/page_store/savepoint.rs
- src/tree_store/table_tree.rs
This restores and fixes the optimization that was removed in baa86e7fe1b6b07acd0568f504d49404a19710d6
restore_savepoint() now scales with the number of database modifications since the savepoint was captured, rather than the size of the database
savepoint_benchmark is now ~35x faster for an 8GiB database file
Benchmarks:
master:
```
+---------+----------+------------------------+---------------------+
| DB size | insert() | persistent_savepoint() | restore_savepoint() |
+===================================================================+
| 129MiB  | 7693ns   | 685us                  | 18807us             |
|---------+----------+------------------------+---------------------|
| 257MiB  | 7456ns   | 510us                  | 62092us             | …
```
> Optimize restore_savepoint()

- benches/common.rs
- benches/int_benchmark.rs
- benches/large_values_benchmark.rs
- benches/lmdb_benchmark.rs
In this PR, I introduce the compaction of the LMDB database. It requires compacting the data into another file and reopening the environment afterward.
The following results were run on my iMac M3 computer. I do not understand how the individual writes of LMDB and RocksDB are so low compared to the README you provided on GitHub 🤔
|                           | redb       | lmdb       | rocksdb        | sled       | sanakirja  |
|---------------------------|------------|------------|----------------|------------|------------|
| bulk load                 | 2652ms     | 1513ms     | 8188ms         | 7168ms     | **1346ms** |
| individual writes         | 405ms      | 7ms        | **4ms**        | 426ms      | 68ms       |
| batch writes              | 4880ms     | 2776ms     | **324ms** …
> LMDB comparison benchmark improvements

- README.md
- benches/lmdb_benchmark.rs
Show before and after size instead of compaction time. Compaction time wasn't a very meaningful comparison, since redb does compaction in-place, where as lmdb does compaction by writing a new file
> Update compaction benchmark

- src/tree_store/btree.rs
Previously all freed pages went through the transactional free mechanism. This commit changes it to reuse dirty pages
> Optimize retain() and retain_in()

- examples/multithread.rs
I've seen a couple questions pop up in the issues about using `redb` in a multi-threaded context or async-task context such as #555. I thought it might be useful to have an example of what that might look like. If anything's incorrect or there are changes that would make this more representative, just let me know!
> Add multithreaded example

- Cargo.toml
- benches/common.rs
- benches/lmdb_benchmark.rs
I was curious about how redb fairs against [fjall](https://github.com/fjall-rs/fjall).
Others might be as well
> Add fjall 2.5 to benchmark suite

- Cargo.toml
- benches/int_benchmark.rs
- benches/large_values_benchmark.rs
- benches/lmdb_benchmark.rs
Summary
* Make a lot of values module-level constants
* Use a sync barrier in multi-threaded sections to reduce variance
* Use rng fill functions whenever possible
* Add some basic configuration to Rocksdb. These should be closer to Fjall defaults, for example.
* Instantiate an env_logger instance. This is a noop in practice, but helps development.
> Small improvements to the benchmarks

- crates/redb-bench/benches/common.rs
- crates/redb-bench/benches/multithreaded_insert_benchmark.rs
- crates/redb-derive/tests/derive_tests.rs
- examples/bincode_keys.rs
- examples/int_keys.rs
- examples/multithread.rs
- fuzz/fuzz_targets/fuzz_redb.rs
- src/db.rs
- src/lib.rs
- src/tree_store/page_store/header.rs
- src/types/chrono_v0_4.rs
- src/types/uuid.rs
- tests/backward_compatibility.rs
- tests/basic_tests.rs
- tests/integration_tests.rs
- tests/multimap_tests.rs
- tests/multithreading_tests.rs
This prepares the API to support opening databases in read-only mode, where multiple processes can open the same database
> Move begin_read() and cache_stats() to trait

- fuzz/fuzz_targets/fuzz_redb.rs
- src/db.rs
- src/transactions.rs
- src/tree_store/page_store/cached_file.rs
- src/tree_store/page_store/file_backend/fallback.rs
- src/tree_store/page_store/file_backend/unix.rs
- src/tree_store/page_store/file_backend/windows.rs
- src/tree_store/page_store/in_memory_backend.rs
- src/tree_store/page_store/page_manager.rs
- tests/integration_tests.rs
The WriteTransaction::commit() API is
problematic when used with barrier sync, since there is no way to report
an error that might occur while writing out the data.
Applications that need this feature can implement it with a custom
StorageBackend. It was only implemented on macOS and called fcntl() with
F_BARRIERFSYNC. On all other platforms Durability::Eventual was
equivalent to Durability::Immediate
> Remove Durability::Eventual

- src/db.rs
- src/transactions.rs
- src/tree_store/mod.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
This avoids some scenarios where a dirty database is opened, which causes a repair, but then shrinks in size invalidating the allocator state hash, which then causes check_integrity() to perform a second repair
> Disable database shrinking during repair

- src/db.rs
- src/error.rs
- src/lib.rs
- src/tree_store/mod.rs
- src/tree_store/page_store/backends.rs
- src/tree_store/page_store/file_backend/optimized.rs
- src/tree_store/page_store/mod.rs
- src/tree_store/page_store/page_manager.rs
- tests/basic_tests.rs
This allows a database to be opened by multiple processes, concurrently, in read-only mode
Fixes #958
Fixes #811
> Add ReadOnlyDatabase and Builder::open_read_only

- Cargo.toml
- justfile
- src/lib.rs
- src/tree_store/page_store/file_backend/optimized.rs
As `FileExt` trait is not getting stabilized [anytime soon](https://github.com/rust-lang/rust/issues/71213#issuecomment-1097758095) on WASI, I added the implementations of `read_exact_at` and `write_all_at` in `redb` itself as these are the only two functions that being used from the trait implementation. WASIp2 currently does not have this trait implemented as all, so with this addition, we get support for WASIp2 and we also eliminate the requirement of nightly toolchain for compiling on WASI platforms.
> Support WASI preview 2 and all WASI platforms on stable toolchain

- src/tree_store/page_store/lru_cache.rs
Shrink hash maps used in the page cache because iterating over them takes time proportional to the capacity of the hash map, and they become very large during large transactions, slowing down future small transactions
> Improve cache flush performance

- src/tree_store/page_store/file_backend/fallback.rs
Relates to #1065.
Version 3.0 introduced `FileBackend::new_internal` which is used by `Builder::open_read_only`. This method is currently missing from the fallback implementation of `FileBackend` (used when not on Windows, Unix, or WASI), causing compilation failures on targets like WASM (see error log below).
```
> cargo clippy -p redb@3 --target wasm32-unknown-unknown
Compiling redb v3.0.2 (/projects/redb)
error[E0599]: no function or associated item named `new_internal` found for struct `tree_store::page_store::file_backend::fallback::FileBackend` in the current scope
--> src/db.rs:1193:35
|
1193 |             Box::new(FileBackend::new_internal(file, true)?),
|                                   ^^^^^^^^^^^^ function or associated item not found in …
```
> Fix fallback implementation of `FileBackend`
