benches/lmdb_benchmark.rs
src/db.rs
src/error.rs
src/lib.rs
src/table.rs
src/transactions.rs

Add benchmark and add interfaces to get a sense for how they will work

Toy implementation

---

Cargo.toml
benches/lmdb_benchmark.rs
deny.toml
src/db.rs
src/lib.rs
src/storage.rs
src/table.rs
src/transactions.rs
tests/integration_tests.rs

Storage is now persistent, but insert()/get() are both O(n)

Linear-scan implementation with mmap

---

src/storage.rs
src/table.rs

Implement len() & is_empty()

---

src/storage.rs
src/table.rs
src/transactions.rs

Implement transaction abort

---

src/table.rs
src/transactions.rs

Implement insert_reserve() for WriteTransaction

---

src/storage.rs
src/table.rs
src/transactions.rs

Implement remove()

---

src/btree.rs
src/storage.rs
src/table.rs
src/transactions.rs

Implement range queries

---

src/btree.rs
src/storage.rs
src/table.rs
src/transactions.rs

Implement reverse range query

---

benches/common.rs
benches/lmdb_benchmark.rs
src/btree.rs
src/db.rs
src/storage.rs
src/table.rs
src/transactions.rs
tests/integration_tests.rs

Add support for multiple tables

---

Makefile
benches/common.rs
src/btree.rs
src/db.rs
src/lib.rs
src/storage.rs
src/table.rs
src/transactions.rs
src/types.rs
tests/integration_tests.rs

Add support for custom ordering of keys

---

src/btree.rs
src/db.rs
src/page_manager.rs
src/storage.rs
src/table.rs
src/transactions.rs
tests/integration_tests.rs

Balance btree during insertion

---

src/btree.rs
tests/integration_tests.rs

Also fix bug deleting from trees with more than 2 levels

Balance btree during deletion

---

src/btree.rs

This speeds up our benchmark by ~1.8x

Switch to order 50 btree

---

src/btree.rs

Use binary search within index pages for lookup

---

src/btree.rs

Improves lookup performance by a couple percent

Switch some assert!s to debug_assert!

---

src/btree.rs
src/db.rs
src/error.rs
src/lib.rs
src/multimap_table.rs
src/storage.rs
src/table.rs
src/transactions.rs

Multimap support

---

Makefile
pyproject.toml

Improve maturin integration

---

benches/lmdb_benchmark.rs
src/btree.rs
src/db.rs
src/multimap_table.rs
src/page_manager.rs
src/storage.rs
src/table.rs
src/transactions.rs
tests/integration_tests.rs

Memory is now freed when it is no longer in use
Fixes #69

Implement MVCC transactions

---

src/btree.rs
tests/integration_tests.rs

Deleting a key could delete other keys as well, due to the tree repair
code dropping pages that were not adjacent to the page that needed
repair

Fix bug in deletion code path

---

src/db.rs

Allow string literals as names and paths

---

docs/design.md
src/multimap_table.rs
src/transactions.rs
src/tree_store/base_types.rs
src/tree_store/btree_utils.rs
src/tree_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs

Switch to modified B-tree

---

src/db.rs
src/tree_store/btree_utils.rs

Minor cleanups

---

docs/design.md
src/db.rs
src/lib.rs
src/multimap_table.rs
src/transactions.rs
src/tree_store/base_types.rs
src/tree_store/btree_utils.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs

Better crash safety

---

docs/design.md
src/multimap_table.rs
src/transactions.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Non durable commit

---

src/tree_store/btree_utils.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Two tables could end up being assigned the same table id

Fix bug in table creation which could lead to data corruption

---

src/tree_store/btree_utils.rs
src/tree_store/page_store/page_manager.rs
src/types.rs
tests/integration_tests.rs

Fix ignored tests

---

benches/common.rs
src/db.rs
src/lib.rs
src/multimap_table.rs
src/table.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Improvements to public API

---

src/db.rs
src/error.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Add better error message for leaked write transactions

---

src/db.rs
src/tree_store/btree_utils.rs
src/tree_store/page_store/page_allocator.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Implement buddy allocator

---

src/db.rs
src/error.rs
src/tree_store/mod.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
tests/integration_tests.rs

Add resize support

---

src/tree_store/btree_utils.rs
src/tree_store/page_store/mmap.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs

Fix soundness issues

---

benches/lmdb_benchmark.rs
src/db.rs
src/multimap_table.rs
src/table.rs
src/tree_store/btree_utils.rs
src/tree_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Refactor storage to use multiple btrees

---

benches/lmdb_benchmark.rs
src/multimap_table.rs
src/table.rs
src/tree_store/btree_iters.rs
src/types.rs
tests/basic_tests.rs

Various cleanups & more primitive type support

---

src/tree_store/btree_utils.rs
tests/integration_tests.rs

Deleting a key from the last leaf of an internal node could cause the
other entries to be dropped, if the leaf became partial and needed to be
merged, due to a bug in the child repair code

Fix regression

---

src/db.rs
src/error.rs
tests/integration_tests.rs

Include table name in Error::TableAlreadyOpen

---

benches/lmdb_benchmark.rs
examples/int_keys.rs
src/db.rs
src/multimap_table.rs
src/table.rs
src/tree_store/btree_utils.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/basic_tests.rs
tests/integration_tests.rs
tests/multimap_tests.rs

Minor cleanups and add Database::create()

---

src/db.rs
src/multimap_table.rs
src/table.rs
src/tree_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/multithreading_tests.rs

Make Database Sync+Send

---

benches/common.rs
examples/int_keys.rs
src/table.rs
src/tree_store/btree_utils.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/basic_tests.rs
tests/integration_tests.rs

Simplify return type of .get()

---

src/db.rs
src/error.rs
tests/integration_tests.rs

Improve error returned when database does not exist

---

src/tree_store/btree_base.rs
src/tree_store/btree_utils.rs
src/tree_store/storage.rs
tests/basic_tests.rs

Add more storage statistics to Database::stats()

---

benches/common.rs
examples/int_keys.rs
src/db.rs
src/lib.rs
src/table.rs
src/tree_store/btree_utils.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/basic_tests.rs
tests/integration_tests.rs
tests/multimap_tests.rs
tests/multithreading_tests.rs

Introduce TableDefinition abstraction

---

src/tree_store/storage.rs

Improve DbStats documentation

---

src/db.rs
src/multimap_table.rs
src/table.rs
src/tree_store/storage.rs
src/types.rs
tests/integration_tests.rs
tests/multimap_tests.rs

Add runtime type checking of tables

---

src/db.rs
src/lib.rs
src/tree_store/mod.rs
src/tree_store/storage.rs
tests/basic_tests.rs

Improvements to DatabaseStats struct

---

Makefile
src/tree_store/btree_iters.rs
src/tree_store/btree_utils.rs
src/tree_store/page_store/page_allocator.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Fix double free

---

src/tree_store/btree_iters.rs
src/tree_store/btree_utils.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Report freed table storage space as metadata

---

src/db.rs
src/lib.rs
src/tree_store/page_store/mmap.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/integration_tests.rs

The existing tests pass, but I didn't add any tests for the new durability level.
Why kinds of tests would be appropriate?

Add three levels of durability

---

.github/workflows/ci.yml
src/python.rs

I also added a clippy run, but it had a bunch of scary complaints, so I gave up.

Check formatting on CI

---

docs/design.md
src/tree_store/page_store/grouped_bitmap.rs
src/tree_store/page_store/page_manager.rs

Use a region based approach, which will allow for dynamic growth

Restructure memory management

---

src/db.rs
src/tree_store/page_store/buddy_allocator.rs
src/tree_store/page_store/mmap.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/storage.rs
tests/integration_tests.rs

Dynamic database file growth

---

src/tree_store/btree_utils.rs

This improves the delete benchmark by ~30%

Optimize page reuse in delete code path

---

.gitignore
Cargo.toml
Makefile
fuzz/.gitignore
fuzz/Cargo.toml
fuzz/fuzz_targets/common.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/tree_store/page_store/mmap.rs
src/tree_store/page_store/page_manager.rs
tests/integration_tests.rs

Add fuzzer and fix a bunch of bugs

---

Cargo.toml
Makefile
benches/large_values_benchmark.rs
src/tree_store/btree_mutator.rs
src/tree_store/page_store/base.rs

Optimize inserting into trees containing large values

---

src/transactions.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/btree_mutator.rs
src/tree_store/table_tree.rs

This brings bulk insert performance to within ~25% of lmdb's performance

Optimizations to insert() & remove()

---

Cargo.toml
src/db.rs
src/multimap_table.rs
src/table.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/page_store/page_manager.rs
src/types.rs

Add basic logging support

---

Cargo.toml
benches/int_benchmark.rs
src/db.rs
src/multimap_table.rs
src/table.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/btree_iters.rs
src/tree_store/btree_mutator.rs
src/tree_store/table_tree.rs
src/types.rs
tests/basic_tests.rs

Optimize fixed width storage

---

src/db.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/table_tree.rs
tests/integration_tests.rs

Fixes several crashes when performing certain operations on a table with
fixed width types

Fix crash caused by fixed width optimization

---

src/tree_store/page_store/buddy_allocator.rs
src/tree_store/page_store/grouped_bitmap.rs
src/tree_store/page_store/page_allocator.rs
src/tree_store/page_store/page_manager.rs
tests/integration_tests.rs

Implement dynamic shrinking of database file

---

.github/workflows/ci.yml
src/tree_store/page_store/page_manager.rs

Add CI for i686 target

---

docs/design.md

Document security properties of 1PC+C

---

CHANGELOG.md
README.md
src/db.rs
src/multimap_table.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/mod.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
tests/multimap_tests.rs

Use more efficient multimap table format

---

src/error.rs
src/tree_store/page_store/mmap.rs
tests/integration_tests.rs

Acquire file lock when opening database

---

src/tree_store/page_store/mmap.rs

Be more paranoid about fsync failures

---

src/tree_store/btree_base.rs

This seems to have no performance impact on x86, but it adds < 0.1%
storage overhead assuming 4k pages, and seems like a good idea since all
the page pointers are 8-bytes

Align branch page header to 8-bytes

---

src/db.rs
src/error.rs
src/transactions.rs
tests/integration_tests.rs

Automatically abort transactions on drop

---

.github/workflows/ci.yml

Cache target/ directory in CI

---

src/tree_store/page_store/page_manager.rs

Return Err instead of panic on bad file format version

---

src/transactions.rs
src/tree_store/btree_mutator.rs
src/tree_store/page_store/base.rs
src/tree_store/page_store/page_manager.rs
tests/integration_tests.rs

Fix race during commit

---

benches/large_values_benchmark.rs
benches/lmdb_benchmark.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/tree_store/page_store/page_manager.rs

Closes #342. Let me know what you think of the comments. I wasn't exactly sure about the right terminology to use.

Change write strategy names

---

src/table.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/btree_mutator.rs
src/tree_store/page_store/page_manager.rs

1PC+C worked, but recovering the database from a crash would panic
Fixes #337

Fix 1PC+C checksum corruption

---

src/db.rs
src/error.rs
src/tree_store/page_store/base.rs
src/tree_store/page_store/layout.rs
src/tree_store/page_store/page_manager.rs

Make default region size consistent on 32bit & 64bit platforms

---

src/db.rs
src/tree_store/page_store/page_manager.rs
tests/integration_tests.rs

Fix panic when open() used on a 2PC database

---

src/db.rs
src/lib.rs
tests/integration_tests.rs

Rename DatabaseBuilder to Builder

---

docs/design.md
src/db.rs
src/transactions.rs
src/tree_store/btree_base.rs
src/tree_store/btree_mutator.rs
src/tree_store/page_store/page_manager.rs

Support converting a 1PC+C database to 2PC

---

src/db.rs

It looks like the `live_write_transaction` mutex is being locked, asserted to be `None`, then dropped and re-acquired. I think this introduces a race condition where two transactions could grab the mutex, assert it's `None`, and then proceed.

Prevent parallel writes

---

src/db.rs

I was thinking that this could stand to be deduplicated.

Add `Database::increment_transaction_id`

---

.github/workflows/ci.yml
benches/mmap_page_size_benchmark.rs
benches/syscall_benchmark.rs

Add `windows-latest` os in CI

---

fuzz/fuzz_targets/common.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/error.rs
src/lib.rs
src/transactions.rs
src/tree_store/mod.rs
src/tree_store/page_store/buddy_allocator.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/page_store/region.rs
src/tree_store/page_store/savepoint.rs
tests/integration_tests.rs

Implement savepoints

---

README.md

This is a cool and unique feature, and possibly one that would make redb particularly attractive for some projects, so it seems worth mentioning in the readme.

Mention savepoints and rollbacks in the readme

---

src/db.rs

Add a log message when repairing database

---

Makefile
fuzz/fuzz_targets/common.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs

Multi-threaded fuzzer

---

src/lib.rs
src/transactions.rs
src/tree_store/btree_base.rs
src/tree_store/btree_iters.rs
src/tree_store/page_store/base.rs
src/tree_store/page_store/bitmap.rs
src/tree_store/page_store/buddy_allocator.rs
src/tree_store/page_store/layout.rs
src/tree_store/page_store/mmap.rs
src/tree_store/page_store/mmap/windows.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/page_store/region.rs
src/tree_store/page_store/utils.rs
src/tree_store/page_store/xxh3.rs
src/tree_store/table_tree.rs

resolved #362
ref: <https://github.com/cberner/xxh3/pull/1>
>It'll be easiest for me to review your changes if you submit a series of PRs that touch only a few files and keep the changes to 100 lines or so. That'll help get them merged quickly so that you don't hit too many merge conflicts with other changes
Sorry for going over 100 lines. Commits are separated according to the content, but if it is necessary to divide the pull request for enabling the clippy option, I will divide it.

Enable the `cast_*` clippy option to deny

---

src/db.rs
src/multimap_table.rs
src/table.rs
src/transactions.rs
src/tree_store/btree_iters.rs
src/tree_store/mod.rs
src/tree_store/page_store/base.rs
src/tree_store/table_tree.rs
tests/integration_tests.rs
tests/multimap_tests.rs

Implement Iterator for RangeIter

---

src/multimap_table.rs
src/table.rs

Unhide iterator type

---

src/db.rs

This avoids allocating a new transaction id for read transactions, and instead just reference counts the write transaction ids

Reference count transaction ids

---

src/db.rs
tests/integration_tests.rs

Allow create() to open an existing 2PC database

---

src/multimap_table.rs

Document order of multimap value collection iteration

---

src/db.rs
src/lib.rs
src/transaction_tracker.rs
src/transactions.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/page_store/savepoint.rs

Remove lifetime from Savepoint

---

Cargo.toml
Makefile
benches/common.rs
benches/int_benchmark.rs
benches/large_values_benchmark.rs
benches/lmdb_benchmark.rs
src/lib.rs
src/multimap_table.rs
src/table.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/table_tree.rs
src/tuple_types.rs
src/types.rs
tests/basic_tests.rs

Convert RedbValue to use GAT and add support for tuple types

---

src/tree_store/btree_base.rs

Reduce write amplification and fix u16 overflow

---

docs/design.md
src/db.rs
src/tree_store/mod.rs
src/tree_store/page_store/layout.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs

Moves the region tracker to be dynamically allocated inside the data section of a region. This will allow future support for increasing the maximum size of a database after creation, or removing the limit entirely

Change file format

---

src/transactions.rs
src/tree_store/page_store/mmap.rs
src/tree_store/page_store/mmap/unix.rs
src/tree_store/page_store/mmap/windows.rs
src/tree_store/page_store/page_manager.rs

Old mmaps are now garbage collected

Fix quadratic address space usage on Windows

---

benches/int_benchmark.rs
benches/large_values_benchmark.rs
benches/lmdb_benchmark.rs
docs/design.md
examples/int_keys.rs
fuzz/fuzz_targets/common.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/error.rs
src/table.rs
src/transactions.rs
src/tree_store/mod.rs
src/tree_store/page_store/bitmap.rs
src/tree_store/page_store/buddy_allocator.rs
src/tree_store/page_store/layout.rs
src/tree_store/page_store/mmap/windows.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/table_tree.rs
tests/basic_tests.rs
tests/integration_tests.rs
tests/multimap_tests.rs
tests/multithreading_tests.rs

Remove size limit from file format

---

Cargo.toml
benches/lmdb_benchmark.rs

Avoid leaking temp files in benchmark

---

src/tree_store/page_store/page_manager.rs

I'm not sure if there's more to it than this, but it seemed simple so I thought I'd open a PR. Fixes #386.

Don't zero out freed pages

---

benches/common.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/lib.rs
src/multimap_table.rs
src/table.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/btree_iters.rs
src/tree_store/btree_mutator.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/table_tree.rs
src/tuple_types.rs
src/types.rs
tests/basic_tests.rs
tests/integration_tests.rs
tests/multimap_tests.rs
tests/multithreading_tests.rs

Refactor RedbValue usage to allow more flexible lifetimes

---

justfile

The address sanitizer needs nightly, so diable that one flag

Make fuzzer work on stable

---

README.md

Size was removed in https://github.com/cberner/redb/commit/0fadb8fa1acb3d00cf407d0df81794767d404e24

Update README.md to reflect no size limit on Databases

---

benches/common.rs
benches/int_benchmark.rs
benches/large_values_benchmark.rs
benches/lmdb_benchmark.rs
examples/int_keys.rs
fuzz/fuzz_targets/common.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/multimap_table.rs
src/table.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/mod.rs
src/tree_store/page_store/base.rs
src/tree_store/page_store/cached_file.rs
src/tree_store/page_store/file_lock/mod.rs
src/tree_store/page_store/file_lock/unix.rs
src/tree_store/page_store/file_lock/windows.rs
src/tree_store/page_store/header.rs
src/tree_store/page_store/mmap.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
tests/basic_tests.rs
tests/integration_tests.rs
tests/multimap_tests.rs
tests/multithreading_tests.rs

Add non-mmap backend

---

.github/workflows/ci.yml

Hopefully this speeds up the tests

Remove 32bit from CI

---

src/tree_store/page_store/cached_file.rs
src/tree_store/page_store/mmap.rs

Try to fix theoretical cache poisoning

---

src/lib.rs
src/multimap_table.rs
src/table.rs
src/tree_store/table_tree.rs
src/tuple_types.rs
src/types.rs

Make RedbKey and RedbValue pub, but sealed

---

src/table.rs
src/tree_store/btree.rs
src/tree_store/btree_iters.rs
src/tree_store/mod.rs
src/tree_store/page_store/page_manager.rs
tests/basic_tests.rs

Add drain() to Table

---

src/tree_store/page_store/base.rs
src/tree_store/page_store/layout.rs
src/tree_store/page_store/page_manager.rs

Fix usize overflows on 32bit platforms

---

fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/multimap_table.rs
src/table.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/btree_iters.rs
src/tree_store/btree_mutator.rs
src/tree_store/page_store/header.rs
src/tree_store/table_tree.rs
src/tuple_types.rs
src/types.rs
tests/basic_tests.rs
tests/integration_tests.rs
tests/multimap_tests.rs

Change get(), insert()...etc to take impl Borrow<SelfType>

---

src/db.rs
src/error.rs

Documentation improvements

---

src/db.rs
src/multimap_table.rs
src/table.rs
src/tree_store/table_tree.rs
src/tuple_types.rs
src/types.rs

Change redb_type_name() to return a struct

---

src/tree_store/page_store/cached_file.rs
src/tree_store/page_store/mmap/unix.rs

Fixes https://github.com/cberner/redb/pull/495

Fix fuzzing target

---

.github/workflows/ci.yml

Enable fuzzer in CI on MacOS

---

src/db.rs
src/tree_store/mod.rs
src/tree_store/page_store/header.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/page_store/utils.rs

Fix several header::tests on platforms with > 4k page size

---

.github/workflows/ci.yml
benches/lmdb_benchmark.rs
benches/mmap_page_size_benchmark.rs
benches/syscall_benchmark.rs
benches/userspace_cache_benchmark.rs
src/error.rs
src/tree_store/page_store/bitmap.rs
src/tree_store/page_store/buddy_allocator.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/table_tree.rs
src/types.rs
tests/basic_tests.rs
tests/integration_tests.rs

Clippy tends to fail with new warnings every release :/

Pin CI to Rust 1.67

---

src/tree_store/page_store/base.rs

Region headers are 66 pages long, and regions contain 2^32 bytes of data. The extra 66 header pages cause the address_range calculation to overflow a u32

Fix crash when accessing the last 66 pages of a region

---

examples/special_values.rs

Add example showing one way of storing out of band values

---

docs/design.md

This feature is not implemented, and there is no clear path to implementing it (see https://github.com/cberner/redb/issues/360). However, if it becomes possible to implement it in the future, this design should be backward compatible

Update design doc with value alignment design

---

Cargo.toml
benches/multithreaded_insert_benchmark.rs
src/multimap_table.rs
src/table.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/btree_iters.rs
src/tree_store/table_tree.rs
tests/multithreading_tests.rs

This allows inserts into separate tables to be executed concurrently across multiple threads
Fixes #112

Make Table Send

---

Cargo.toml

The new one has better read performance

Update rocksdb version in benchmark

---

src/tree_store/btree.rs

Keep a cached copy of the root page to avoid repeated lookups. This improves the read contention benchmark by ~50%

Optimize contended read transactions

---

examples/special_values.rs
src/db.rs
src/lib.rs
src/transactions.rs
src/tree_store/table_tree.rs
tests/basic_tests.rs
tests/integration_tests.rs

Make list_table() & delete_table() more flexible

---

benches/large_values_benchmark.rs
benches/lmdb_benchmark.rs
docs/design.md
fuzz/fuzz_targets/common.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/lib.rs
src/transaction_tracker.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/btree_mutator.rs
src/tree_store/page_store/header.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/page_store/savepoint.rs
tests/integration_tests.rs

All databases now use checksums

Replace WriteStrategy with new Durability level

---

tests/basic_tests.rs

Hello, it's not much but runned grcov and found that some lines were not covered. Had some time for a little contribution so I tried it out.
<https://github.com/mozilla/grcov#usage>.
In the meantime I had to disable compilation (commented in cargo.toml) of benchmarking, if not Grcov went mad. maybe using a workspace and keeping bench behind a feature gate is worth I don't know.

Raise test line coverage in src/table from 88% to 98%.

---

src/db.rs
src/tree_store/page_store/cached_file.rs
src/tree_store/page_store/header.rs
src/tree_store/page_store/page_manager.rs

Fixes https://github.com/cberner/redb/issues/537

Add check_integrity() to explicitly repair db

---

src/transactions.rs

If there were no data pages to free the post commit free pages were not being stored in the pending free table. This would corrupt any outstanding savepoints

Fix post-commit free page handling

---

src/db.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/page_store/base.rs
src/tree_store/page_store/buddy_allocator.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/table_tree.rs
tests/integration_tests.rs

Implement explicit compaction

---

docs/design.md
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/error.rs
src/transaction_tracker.rs
src/transactions.rs
src/tree_store/page_store/savepoint.rs
src/types.rs
tests/integration_tests.rs

Persistent savepoints

---

.github/workflows/ci.yml
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/error.rs
src/lib.rs
src/multimap_table.rs
src/table.rs
src/transactions.rs
src/tree_store/page_store/cached_file.rs
src/tree_store/page_store/file_lock/unix.rs
src/tree_store/page_store/file_lock/windows.rs
src/tree_store/page_store/header.rs
src/tree_store/page_store/layout.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/table_tree.rs
tests/integration_tests.rs
tests/multimap_tests.rs

Split Error into more granular error types

---

src/error.rs
src/lib.rs

Expose TransactionError

---

src/tree_store/page_store/page_manager.rs

This is unnecessary, since any growth space can still be used

Don't reset layout during rollback

---

src/transactions.rs
src/tree_store/page_store/page_manager.rs

I think this will fix #623 and fix #620

Fix panic after growth failure

---

src/db.rs
src/multimap_table.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/table_tree.rs

Fix panics when repairing some databases

---

src/multimap_table.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/btree_mutator.rs
tests/integration_tests.rs

Fix corruption when calling drain() or drain_filter()

---

src/multimap_table.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/mod.rs
src/tree_store/page_store/cached_file.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/page_store/region.rs

Also improves performance by a few percentage points on write heavy workloads

Cleanup write cache TODOs

---

src/tree_store/btree.rs

Fix panic during repair

---

Cargo.toml

Update msrv to 1.67

---

fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/error.rs
src/tree_store/page_store/base.rs

compact() fixes

---

src/table.rs

docs: note drop behavior for `Drain` and `DrainFilter`

---

src/tree_store/page_store/page_manager.rs

Reduce lock contention

---

README.md

Add link to benchmark in README

---

src/complex_types.rs
src/lib.rs
src/types.rs
tests/basic_tests.rs

Implement RedbValue for Vec<T>

---

src/table.rs
tests/basic_tests.rs

Add ReadableTable::first() and last()

---

src/tree_store/page_store/file_backend/fallback.rs

The `fallback.rs` backend has several small compilation issues; this PR addresses them.

Fix compilation of fallback.rs

---

src/multimap_table.rs

Separate lifetimes on key and value to MultimapTable remove()

---

src/table.rs

Make insert() docs more explicit

---

src/lib.rs
src/table.rs
tests/integration_tests.rs

Unseal table traits

---

src/transactions.rs

Update Durability::None docs

---

src/transactions.rs
tests/integration_tests.rs

Previously pages freed in the oldest transaction that still had a read reference were not freed
Fixes #830

Improve freeing of pages

---

src/db.rs
src/transactions.rs
src/tree_store/mod.rs
src/tree_store/table_tree.rs
src/tree_store/table_tree_base.rs

This makes it harder to misuse and uncovered one bug in the compaction code already

Refactor InternalTableDefinition

---

src/complex_types.rs
src/error.rs
src/lib.rs
src/multimap_table.rs
src/transactions.rs
src/tree_store/btree_base.rs
src/tree_store/page_store/buddy_allocator.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/page_store/savepoint.rs
src/tree_store/table_tree.rs
src/types.rs

These resulted from a merge race between the new clippy checks and the msrv update

Fix clippy errors

---

src/transactions.rs
src/tree_store/page_store/page_manager.rs

Include empty pages in fragmented statistics

---

benches/common.rs
benches/int_benchmark.rs
benches/large_values_benchmark.rs
benches/lmdb_benchmark.rs

This will make it easier to test compaction on rocksdb

Refactor benchmark code

---

src/error.rs
src/transactions.rs
src/tree_store/table_tree.rs
tests/basic_tests.rs

Fixes https://github.com/cberner/redb/issues/947

Add rename_table() and rename_multimap_table()

---

src/tuple_types.rs

Fixes https://github.com/cberner/redb/issues/953.
I made the decision to adapt `SelfType` to be a tuple as well, matching the other tuple impls, but copy over the `AsBytes` type as a simple optimization. I wouldn't mind changing that, though.

Implement Key and Value for (T,)

---

fuzz/fuzz_targets/fuzz_redb.rs

Duplicating the file creates two file descriptors which share the same set of locks, so it is possible to re-open an already open database

Fix theoretical issue in fuzzer

---

CHANGELOG.md
Cargo.toml
docs/design.md
fuzz/fuzz_targets/common.rs
fuzz/fuzz_targets/fuzz_redb.rs
src/db.rs
src/error.rs
src/lib.rs
src/multimap_table.rs
src/table.rs
src/transaction_tracker.rs
src/transactions.rs
src/tree_store/btree.rs
src/tree_store/btree_base.rs
src/tree_store/btree_iters.rs
src/tree_store/btree_mutator.rs
src/tree_store/mod.rs
src/tree_store/page_store/base.rs
src/tree_store/page_store/cached_file.rs
src/tree_store/page_store/header.rs
src/tree_store/page_store/mod.rs
src/tree_store/page_store/page_manager.rs
src/tree_store/page_store/savepoint.rs
src/tree_store/table_tree.rs
tests/backward_compatibility.rs
tests/integration_tests.rs

Implement v3 file format

---

README.md

This small PR updates the `lmdb_benchmark.rs` location in `README.md`.

Update benchmark source

---

CHANGELOG.md
src/complex_types.rs
src/legacy_tuple_types.rs
src/lib.rs
src/types.rs
tests/backward_compatibility.rs
tests/basic_tests.rs

Also adds the Legacy wrapper type for the previous tuple encoding

Optimize encoding of tuple types

---

crates/redb-derive/src/lib.rs
crates/redb-derive/tests/derive_tests.rs

Add derive macro for Key

---

src/tree_store/page_store/base.rs

This allows for a future optimization in which reads can be shortened

Reserve some bits in page numbers for future use

---

.github/workflows/ci.yml
Cargo.toml

Following on from #1084, plus some minor changes.

Run cargo check on `wasm32-unknown-unknown` target

---

src/error.rs

Implement std::Error for SetDurabilityError
